import Head from 'next/head'
import Image from 'next/image'
import Mobilenav from '../components/Mobilenav'
import Sidenav from '../components/Sidenav'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Bottom Nav*/}

      <Mobilenav />

      {/*Side Nav*/}
      <div className=" grid grid-flow-col grid-cols-11">
        <div className="grid col-span-2"><Sidenav/></div>
        <div className="grid col-span-9 text-xl animate-pulse">This is content component placeholder</div>
      </div>
     
      

      {/*Top Nav*/}

      {/*Feed*/}

    </div>
    
  )
}
